checkout/urls.py
from django.conf.urls import url
from checkout.views import *

urlpatterns = [
	url(r'^$', checkout, name='checkout'),
	
]

ecomm/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
	url(r'^', include('profiles.urls', namespace='profiles')),
	url(r'^accounts/', include('allauth.urls')),
    url(r'^checkout', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),


]

profiles/urls.py
from django.conf.urls import url
from profiles.views import *

urlpatterns = [
	url(r'^$', home, name='home'),
	url(r'^about/$', about, name='about'),
	url(r'^contact/$', contact, name='contact'),
	url(r'^profile/$', profile, name='profile'),
]

checkout/models.py
from django.db import models

# Create your models here.

profiles/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
	name        = models.CharField(max_length=120, default='')
	description = models.TextField(default='Add a description')

	def __str__(self):
		return self.name
		

profiles/forms.py
from django import forms

class ContactForm(forms.Form):
	name    = forms.CharField(max_length=100, required=True, help_text='100 characters')
	email   = forms.EmailField(required=True)
	comment = forms.CharField(required=True, widget=forms.Textarea)

checkout/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def checkout(request):
	context = {}
	return render(request, 'checkout/checkout.html', context)

profiles/views.py
from django.shortcuts import render
from profiles.forms import *
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required



# Create your views here.
def home(request):
	args = locals()

	return render(request, 'profiles/home.html', args)

@login_required
def about(request):
	args = locals()

	return render(request, 'profiles/about.html', args)

@login_required
def profile(request):
	user = request.user
	context = {'user': user}
	return render(request, 'profiles/profile.html', context)

def contact(request):
	title = 'Contact Us'
	form = ContactForm(request.POST or None)
	confirm_message = None

	if form.is_valid():
		name = form.cleaned_data['name']
		comment = form.cleaned_data['comment']
		subject = 'Message from MYSITE.com'
		message = '%s %s' %(name, comment)
		emailFrom = form.cleaned_data['email']
		emailTo = [settings.EMAIL_HOST_USER]
		send_mail(subject, message, emailFrom, emailTo, fail_silently=True)

		title = 'Thanks'
		confirm_message = 'Message Sent! We will get back to you shortly.'
		form = None

	context = {'title': title, 'form': form, 'confirm_message': confirm_message}		
	return render(request, 'profiles/contact.html', context)
	

checkout/templates/checkout/checkout.html
{% extends 'profiles/base.html' %}
{% block title%} Checkout {% endblock %}
{% block script %}
{% endblock %}

{% block body%}
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<form action="/charge" method="post" id="payment-form">
					<div class="form-row">
					    <label for="card-element">
					      Credit or debit card
					    </label>
					    <div id="card-element">
					      <!-- a Stripe Element will be inserted here. -->
					    </div>

					    <!-- Used to display Element errors -->
					    <div id="card-errors" role="alert"></div>
					</div>

				  	<button>Submit Payment</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

profiles/templates/profiles/about.html
{% extends 'profiles/base.html' %}

{% block title%} About {% endblock %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<h3>About Me</h3>
			</div>
		</div>
	</div>
	
{% endblock %}

profiles/templates/profiles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <title>{% block title%} Home {% endblock %}</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'profiles/styles.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <a class="navbar-brand" href="{% url 'profiles:home' %}">Social</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profiles:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profiles:contact' %}">Contact</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
        </ul>
        {% endif %}
      </div>
      </div>
    </nav>


    

    {% block body%}
    {% endblock %}



































    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

profiles/templates/profiles/contact.html
{% extends 'profiles/base.html' %}
{% load crispy_forms_tags %}

{% block title%} Contact {% endblock %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<h3>{{ title }}</h3>
				{% if confirm_message %}
					<p>{{ confirm_message }}</p>
				{% endif %}
			</div>
			<div class="col-md-4 ml-auto mr-auto">
				{% if form %}
				<form method="post">
			  		{% csrf_token %}
			  		{{ form|crispy }}
			  		<button type="submit" class="btn btn-primary">Send</button>
			  	</form>
			  	{% endif %}
			</div>
		</div>
	</div>
	
{% endblock %}

profiles/templates/profiles/home.html
{% extends 'profiles/base.html' %}
{% load static %}
{% block title%} Home {% endblock %}

{% block body %}

	<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="container">
      <div class="jumbotron text-center mt-4">
        <h1>Navbar example</h1>
        <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you scroll, this navbar remains in its original position and moves with the rest of the page.</p>
        <a class="btn btn-lg btn-primary" href="../../components/navbar/" role="button">View navbar docs &raquo;</a>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <a href=""> <img src="{% static 'profiles/img/home.jpg' %}" class="img-fluid"> </a>
        </div>

        <div class="col-md-4">
          {% if user.is_authenticated %}
          <h3>Hello {{ user }}</h3>

          {% else %}
          <form class="login" method="POST" action="{% url 'account_login' %}">
            {% csrf_token %}
            <div id="div_id_login" class="form-group"> 
              <label for="id_login" class="form-control-label  requiredField">
                Login<span class="asteriskField">*</span> </label> 
                <div class=""> <input type="text" name="login" placeholder="Username or e-mail" autofocus="autofocus" class="textinput textInput form-control" required="" id="id_login"> </div> </div> <div id="div_id_password" class="form-group"> <label for="id_password" class="form-control-label  requiredField">
                Password<span class="asteriskField">*</span> </label> <div class=""> <input type="password" name="password" placeholder="Password" class="textinput textInput form-control" required="" id="id_password"> </div> </div> <div class="form-group"> <div id="div_id_remember" class="checkbox"> <label for="id_remember" class=""> <input type="checkbox" name="remember" class="checkboxinput" id="id_remember">
                    Remember Me
                </label> </div> </div>
            <a class="button secondaryAction" href="{% url 'account_reset_password' %}">Forgot Password?</a>
            <a class="button secondaryAction" href="{% url 'account_signup' %}">Signup</a>
            <button class="primaryAction btn btn-primary" type="submit">Sign In</button>
          </form>
          {% endif %}
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Company 2017</p>
      </footer>
    </div> <!-- /container -->
	
{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'profiles/base.html' %}
{% block title%} Profile {% endblock %}

{% block body%}
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<p> User Name :  {{ user.username }}</p>
				<p> Email     :  {{ user.email }}</p>
			</div>
		</div>
	</div>
{% endblock %}